name: auth_manager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_cropper: ^3.0.1
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  hexcolor: ^3.0.1
  convex_bottom_bar: ^3.0.0
  contactus: ^1.2.0
  line_awesome_flutter: ^2.0.0
  flutter_screenutil: ^5.3.1
  upgrader: ^6.0.1
  retry: ^3.1.0
  http: ^0.13.4
  date_format: ^2.0.6
  modal_bottom_sheet: ^2.0.1
  url_launcher: ^6.1.0
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  dio: ^5.0.1
  awesome_dialog: ^3.0.2
  font_awesome_flutter:
  shared_preferences: ^2.0.18
  back_button_interceptor: ^6.0.2
  bot_toast: ^4.0.3
  easy_localization: ^3.0.1
  flutter_local_notifications: ^13.0.0
  rxdart: ^0.27.7
  intl_phone_field: ^3.1.0
  #alice:
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  firebase_messaging_platform_interface: ^4.2.14
  carousel_slider: ^4.1.1
  webview_flutter: ^4.0.6
  youtube_player_flutter: ^8.0.0
  local_auth: ^2.1.6
  google_sign_in: ^6.0.2
  firebase_auth: ^4.2.9
  flutter_html: ^3.0.0-alpha.3
  flutter_material_pickers: ^3.1.2
  flutter_cached_pdfview: ^0.4.1
#  flutter_pdfview: ^1.3.0
  connection_notifier: ^1.0.1

  image_picker: ^0.8.6+4
  change_app_package_name: ^1.1.0
#  image_cropper:
  share_plus: ^6.3.1
  map_launcher: ^2.5.0+1
  the_apple_sign_in: ^1.1.1
  flutter_signin_button: ^2.0.0
  file_picker: ^5.2.5
  flutter_rating_bar: ^4.0.1
  package_info_plus: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1

flutter_icons:
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff" #"assets/icon/logo.png"
  adaptive_icon_foreground: "assets/images/App Icon.png"
  android: true
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/app-logo.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/error-icon.png
    - assets/images/check.png
    - assets/images/background.png
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

    - family: PNU
      fonts:
        - asset: assets/fonts/PNU-Bold.ttf
        - asset: assets/fonts/PNU-Light.ttf
        - asset: assets/fonts/PNU-Medium.ttf
        - asset: assets/fonts/PNU-Regular.ttf
